package com.global.api.entities;

import lombok.Getter;
import lombok.Setter;

@Getter
@Setter
public class Action {

    /**
     * Represents a unique identifier generated by Global Payments to identify an action.
     */
    private String id;
    /**
     * Indicates the specific action taken.
     */
    private String type;
    /**
     * Represents Global Payments time indicating when the object was created in ISO-8601 format.
     */
    private String timeCreated;
    /**
     * Represents the result of the action executed.
     */
    private String resultCode;
    /**
     * Represents id of the app that was used to create the token.
     */
    private String appId;
    /**
     * Represents the name of the app the user gave to the application.
     */
    private String appName;
}
